first_str = input("Enter first number :")
second_str = input("Enter second number :")
third_str = input("Enter third number :")
first = float(first_str)
second = float(second_str)
third = float(third_str)
sum = first+second+third
product = first*second*third
average = (first+second+third)/3
print("Sum = " + str(sum))
print("Product = " + str(product))
print("average = " + str(average))